name: Pin Conda Environments

on:
  workflow_dispatch:

env:
  BRANCH_NAME: update-conda-env-pinnings

concurrency:
  group: pin-conda-envs-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  pin-linux-64:
    name: Pin conda envs (linux-64)
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main

      - name: Pin conda environments
        uses: snakemake/snakedeploy-github-action@v1
        with:
          subcommand: pin-conda-envs
          args: workflow/envs/*.yaml

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ github.token }}
          branch: ${{ env.BRANCH_NAME }}
          base: main
          add-paths: workflow/envs/*.linux-64.pin.txt
          commit-message: "update linux-64 conda pins"
          title: "Update conda env pins"
          body: |
            Automated conda pin refresh generated by the pin-conda-envs workflow.
          draft: false
